# Put the line below in ~/.bashrc or ~/bash_profile:
#
#   eval "$(kite jump shell bash)"
#   # set the bind func name is: j
#   eval "$(kite jump shell bash --bind j)"
#
# The following lines are autogenerated:
__jump_prompt_command() {
  local status=$?
  kite jump chdir && return $status
}

# completion func for {{bindFunc}}
__jump_hint() {
  local term="${COMP_LINE/#{{bindFunc}} /}"
  echo $(kite jump hint "$term")
}

{{bindFunc}}() {
  local dir
  dir=$(kite jump get "$@")
  test -d "$dir" && cd "$dir"
}

[[ "$PROMPT_COMMAND" =~ __jump_prompt_command ]] || {
  PROMPT_COMMAND="__jump_prompt_command;$PROMPT_COMMAND"
}
complete -o dirnames -C '__jump_hint' {{bindFunc}}

# add alias for: kite jump
alias kj="kite jump"