### test request
GET http://{{host}}/api/item?id=99
Accept: application/json

### post json example
# comment line
POST http://{{host}}/posts/add
custom-key: value
#custom-key1: value1
Content-Type: application/json

{
  "status": "draft",
  "title": "post title",
  "content": "post content",
  "type": "blog",
  "author_id": 123,
  "author": "inhere"
}

### post form example

POST http://{{host}}/posts/add
custom-key: value
Content-Type: application/x-www-form-urlencoded

title=post title&content=post content

###

