<?php
/**
 * @var string $_staticPath
 */
?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link rel="stylesheet" href="<?= $_staticPath ?>/css/bulma.min.css">
</head>
<body>
<div class="columns">
  <div class="column is-half is-offset-one-quarter">
    <h1>
      JSON5 <=> JSON
    </h1>
  </div>
</div>

<div class="columns is-mobile">
  <div class="column">
    <label for="json5-data">JSON5 Data</label>
    <textarea name="json5-data" id="json5-data" cols="30" rows="10">

    </textarea>
  </div>
  <div class="column">
    <label for="json-data">JSON Data</label>
    <textarea name="json-data" id="json-data" cols="30" rows="10"></textarea>
  </div>
</div>
</body>
<script src="<?= $_staticPath ?>/libs/json5.min.js"></script>
<script>
  // JSON5.parse()
</script>
</html>
