name: Tag-release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Test on php ${{ matrix.php}}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        php: 7.3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # usage refer https://github.com/shivammathur/setup-php
      - name: Setup PHP
        timeout-minutes: 5
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php}}
          tools: pecl, php-cs-fixer, phpunit
          extensions: mbstring, dom, fileinfo, mysql, openssl # , swoole-4.4.19 #optional, setup extensions
          ini-values: post_max_size=56M, short_open_tag=On #optional, setup php.ini configuration
          coverage: none #optional, setup coverage driver: xdebug, none

      - name: Install dependencies
        run: composer install --no-progress --no-suggest

      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md

      - name: Build phar package
        run: php -d phar.readonly=0 bin/kite phar:pack -o kite.phar

      - name: Post to github assets
        run:

